# Centralized configuration for agents hosted by the gallery.
agents:
  RAG:
    description: "Uses Vertex AI and requires specific GCP project and location."
    environment:
      # Use Vertex AI instead of API Keys
      GOOGLE_GENAI_USE_VERTEXAI: TRUE
      # Unset API keys to force Application Default Credentials
      UNSET_ENV_VARS:
        - GOOGLE_API_KEY
        - GEMINI_API_KEY
      # Project and Location for Vertex AI
      GOOGLE_CLOUD_PROJECT: "primaryproject-305315"
      GOOGLE_CLOUD_LOCATION: "us-central1"
      # Agent-specific values
      RAG_CORPUS: "projects/primaryproject-305315/locations/us-central1/ragCorpora/5685794529555251200"

  some-other-agent:
    environment:
      SOME_CUSTOM_VARIABLE: "value"
